name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Khởi tạo các Services (Database, Cache, Message Broker) ngay trên máy ảo Github Actions
    services:
      # Cấu hình PostgreSQL
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ci_test_pass
          POSTGRES_DB: e-walletdbs
        ports:
          - 5432:5432
        # Đảm bảo DB khởi động xong mới chạy test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      # Cấu hình Redis
      redis:
        image: redis:7
        ports:
          - 6379:6379
          
      # Cấu hình RabbitMQ
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672

   # Bắt đầu các bước chạy test
    defaults:
      run:
        working-directory: ./E-Wallet

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      env:
          SPRING_DATASOURCE_PASSWORD: ci_test_pass
      run: mvn -B clean package --file pom.xml
      
    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: e-wallet-app
        path: E-Wallet/target/*.jar
        retention-days: 1
