name: Java CI with Maven


# 1. TRIGGER: Khi nào thì ci này được chạy?
on:
  push:
    branches: [ "main", "dev" ]

  # Chạy cả khi có người tạo Pull Request để review code trước khi merge
  pull_request:
    branches: [ "main", "dev" ]

# 2. Công việc cần làm gì?
jobs:

  build:
    runs-on: ubuntu-latest # GitHub cấp cho ta 1 máy ảo Linux miễn phí
    
    # Thiết lập thư mục làm việc mặc định cho các bước (vì project maven nằm trong thư mục con)
    defaults:
      run:
        working-directory: ./E-Wallet

    steps:

    # 1. Lấy code từ repo về máy ảo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cài đặt môi trường
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # Tự động cache thư viện maven để các lần chạy sau nhanh hơn

    # 3. Chạy Maven để Compile và Test
    - name: Build and Test with Maven
      run: mvn -B clean package --file pom.xml
      
    # Tùy chọn: Upload file .jar sau khi build thành công (để có thể tải về xem thử)
    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: e-wallet-app
        path: E-Wallet/target/*.jar
        retention-days: 1
